### ISSUE TITLE
SpoolSample 

### ISSUE THREAD

**Issue by cyberfreaq** [Flangvik/SharpCollection#4]
Hi,

you mentioned "SpoolSample" in your "Sources / Credits" section but I couldn't find the executable in your repo. 
Could you add this one?

Best regards

**Comment by Flangvik** [comment]
Hey @cyberfreaq! That's correct, I think I began to add it, but quickly discovered it was a hot mess to automate / CDI. Due to both native and C# dependences, as well a custom PowerShell script that needs to run.  I might get into adding it later, but for now, it's simply too complicated for my effort. Sry!
